/**
 * v5 router: maps task types to the documents a subagent needs.
 *
 * Implements §2 (Document Routing) and §9.4 (backtracking prevention) of
 * `docs/REFACTOR-REQUIREMENTS.md`. The shape is illustrated in
 * `docs/v5-diagrams/01-document-routing.html`.
 *
 * Design:
 * - The `TASK_TYPE_ROUTES` map is the single source of truth. Adding a new
 *   task type only requires extending this map.
 * - Each route is an ordered list of `{ path, scope, optional }`. `path` may
 *   contain `{slug}` which is substituted at resolve time.
 * - `resolveRoute` returns paths only — it does not read files. Use
 *   `lib/v5/context-packet.mjs` to load and size content.
 * - When `stage` is `ux` or `ui` and the requested taskType is `architecture`,
 *   the route is deferred (no docs returned) to prevent backtracking into
 *   architecture decisions while UX/UI are still being explored. §9 of
 *   `docs/REFACTOR-REQUIREMENTS.md` mandates strict UX → UI → Architecture →
 *   Build ordering.
 *
 * No external dependencies — stdlib only.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Hard rule about decision visual fragments. Surfaced verbatim into every
 * dispatch packet for UX, UI, and Architecture routes via `usageNote`. The
 * same wording appears in the four routing docs and the three v5 skills.
 *
 * Keep this string identical to the wording in:
 *   - control/v5/routing/UX-PATTERNS.md
 *   - control/v5/routing/UI-REQUIREMENTS.md
 *   - control/v5/routing/ARCHITECTURE.md
 *   - control/v5/routing/ROUTING-MANIFEST.md
 *   - skills/mc/SKILL.md
 *   - skills/mc-braindump/SKILL.md
 *   - skills/mc-build/SKILL.md
 */
const VISUAL_FRAGMENT_RULE =
  'You MUST NOT write HTML for a decision card by hand. Every decision in ' +
  'decisions.json requires a sibling fragment file generated by ' +
  '`node lib/v5/cli/build-decision.mjs <slug> <decision-id>`. If a decision ' +
  'has no fragment, the feature page falls back to plain text cards — this ' +
  'is a failure mode, not an acceptable state.';

const ROUTING_DOCS_NOTE =
  'Consult the routing docs in `control/v5/routing/` before producing any ' +
  'visual artifacts. Do not hand-author decision card HTML — see the visual ' +
  'fragment contract in `control/v5/routing/ROUTING-MANIFEST.md`.';

/**
 * Universal rule #1 — DECISIONS go through the dashboard, not chat.
 *
 * Any UX, UI, or architecture choice that gets recorded into the feature
 * spec is a *decision*. Decisions are captured by writing to
 * `decisions.json`, building the visual fragment via the CLI, and opening
 * the dashboard — never by `AskUserQuestion` or text prose. The dashboard
 * is the canonical surface for picking among UX/UI/architecture options.
 *
 * Listed first in UNIVERSAL_INSTRUCTIONS because the most common failure
 * mode is reaching for `AskUserQuestion` when the user input is actually
 * a decision. Reading top-down, agents see the decision path before they
 * see the clarifying-question path.
 */
export const DECISION_CAPTURE_RULE =
  'DECISIONS (any UX, UI, or architecture choice recorded into the feature ' +
  'spec) MUST be captured on the dashboard, NOT via `AskUserQuestion` or ' +
  'plain chat prose. The canonical sequence is: (a) dispatch the ' +
  '`mc-decide` skill, OR follow its steps directly — write the decision ' +
  '(question, 3–4 options, selected, category) into ' +
  '`control/v5/features/{slug}/decisions.json` via `lib/v5/decisions.mjs`; ' +
  '(b) run `node lib/v5/cli/build-decision.mjs <slug> <decision-id>` to ' +
  'generate the visual fragment; (c) call `openDashboard({slug, anchor: ' +
  '"decisions"})` from `lib/v5/auto-launch.mjs` so the user picks on the ' +
  'dashboard. Asking "which of these UX/UI/architecture options should we ' +
  'use?" through `AskUserQuestion` is a routing failure — the dashboard ' +
  'visualizes the choice, the chat does not.';

/**
 * Universal rule #2 — CLARIFYING QUESTIONS use a structured ask.
 *
 * Scoping questions, disambiguation, and plain Q&A that do NOT capture a
 * UX / UI / architecture choice. These belong in the structured-ask tool
 * (Claude Code: `AskUserQuestion`; other harnesses: pause and ask in
 * chat) — never buried in prose, never resolved by guessing.
 */
export const USER_QUESTION_RULE =
  'CLARIFYING QUESTIONS (scope, disambiguation, plain Q&A that does NOT ' +
  'capture a UX/UI/architecture choice) MUST be surfaced through a ' +
  'structured ask, and execution MUST pause until the user responds. In ' +
  'Claude Code, use the `AskUserQuestion` tool with 1–4 mutually exclusive ' +
  'options. In Cursor or other harnesses without a dedicated question tool, ' +
  'stop execution and ask the user directly in the conversation before ' +
  'continuing. Hiding questions in long prose, or proceeding on an ' +
  'assumption you should have verified, is a routing failure. If the ' +
  'question is actually a decision (a UX/UI/architecture choice), do NOT ' +
  'use this path — see the DECISION_CAPTURE_RULE above.';

/**
 * Instructions every dispatch packet carries, independent of task type or
 * stage. Exported so `lib/v5/context-packet.mjs` can prepend them ahead of
 * route-specific `usageNote` strings, and so tests can pin the canonical
 * set without duplicating string literals.
 *
 * Order matters: DECISION_CAPTURE_RULE first so agents see the dashboard
 * path before the chat path. The most common failure mode is reaching for
 * `AskUserQuestion` when the user input is actually a decision.
 */
export const UNIVERSAL_INSTRUCTIONS = Object.freeze([
  DECISION_CAPTURE_RULE,
  USER_QUESTION_RULE,
]);

/**
 * Canonical task type → route map.
 *
 * Each entry is `{ docs, usageNote }`:
 *  - `docs` is an ordered list of `{ path, scope, optional }`:
 *    - `path` is a repo-relative path. `{slug}` tokens are substituted by
 *      `resolveRoute` if a `slug` is provided.
 *    - `scope` is a short tag used in logging and UI display.
 *    - `optional` indicates the doc may not exist on disk (e.g., per-feature
 *      files that only appear after the feature has produced output).
 *  - `usageNote` is a string the router forwards into every context packet's
 *    `instructions[]` array. Used to surface the visual fragment contract
 *    (do not hand-write decision HTML) to dispatched subagents.
 */
export const TASK_TYPE_ROUTES = Object.freeze({
  'ui-implementation': {
    docs: [
      { path: 'control/v5/routing/UI-REQUIREMENTS.md', scope: 'ui-requirements', optional: false },
      {
        path: 'control/layout/diagrams/ui-options/template.html',
        scope: 'ui-primitives',
        optional: false,
      },
      {
        path: 'control/v5/features/{slug}/layout/wireframes/',
        scope: 'wireframes',
        optional: true,
      },
    ],
    usageNote: VISUAL_FRAGMENT_RULE,
  },
  'ux-decisions': {
    docs: [
      { path: 'control/v5/routing/UX-PATTERNS.md', scope: 'ux-patterns', optional: false },
      {
        path: 'control/layout/diagrams/ux-flow/template.html',
        scope: 'ux-primitives',
        optional: false,
      },
      {
        path: 'control/v5/features/{slug}/ux-flow.html',
        scope: 'current-flow',
        optional: true,
      },
    ],
    usageNote: VISUAL_FRAGMENT_RULE,
  },
  architecture: {
    docs: [
      { path: 'control/v5/routing/ARCHITECTURE.md', scope: 'architecture', optional: false },
      { path: 'control/v5/tech-stack/stack.json', scope: 'stack', optional: true },
      {
        path: 'control/layout/diagrams/architecture/template.html',
        scope: 'architecture-primitives',
        optional: false,
      },
    ],
    usageNote: VISUAL_FRAGMENT_RULE,
  },
  research: {
    docs: [
      { path: 'control/v5/routing/UX-PATTERNS.md', scope: 'patterns', optional: false },
      {
        path: 'control/v5/features/{slug}/braindump.md',
        scope: 'user-spec',
        optional: true,
      },
    ],
    usageNote: ROUTING_DOCS_NOTE,
  },
  build: {
    docs: [
      {
        path: 'control/v5/features/{slug}/phases/',
        scope: 'phase-plans',
        optional: false,
      },
      { path: 'control/v5/routing/BUILD-GATES.md', scope: 'build-gates', optional: false },
      {
        path: 'control/v5/routing/ARCHITECTURE-MVVM.md',
        scope: 'mvvm-rules',
        optional: false,
      },
      {
        path: 'control/v5/features/{slug}/spec.md',
        scope: 'spec',
        optional: true,
      },
    ],
    usageNote: ROUTING_DOCS_NOTE,
  },
  brainstorm: {
    docs: [
      { path: 'control/v5/routing/UX-PATTERNS.md', scope: 'patterns', optional: false },
      {
        path: 'control/v5/features/{slug}/braindump.md',
        scope: 'product-context',
        optional: true,
      },
    ],
    usageNote: ROUTING_DOCS_NOTE,
  },
});

/**
 * Return the list of supported task types.
 *
 * @returns {string[]}
 */
export function listTaskTypes() {
  return Object.keys(TASK_TYPE_ROUTES);
}

/**
 * Canonical pipeline phases — the ordered set of stages a feature passes
 * through. The router uses this to enforce §9 ordering (no skipping ahead,
 * no backtracking after the gate).
 */
const PHASE_ORDER = ['ux', 'ui', 'architecture', 'build'];

/**
 * For each canonical phase, the task type the orchestrator should pick by
 * default when no explicit taskType is supplied (e.g. from a pickup prompt).
 *
 * Stage values that aren't canonical phases (dashboard buckets like
 * "needs-input" / "ready" / "in-progress" / "complete" or legacy "mock") map
 * to the most reasonable default for that bucket.
 */
const STAGE_TO_DEFAULT_TASK_TYPE = Object.freeze({
  // canonical phases
  ux: 'ux-decisions',
  ui: 'ui-implementation',
  architecture: 'architecture',
  build: 'build',
  // dashboard buckets / legacy
  brainstorm: 'brainstorm',
  'needs-input': 'brainstorm',
  ready: 'build',
  'in-progress': 'build',
  complete: 'build', // re-entry for fixes/maintenance
  mock: 'ui-implementation',
});

/**
 * Map a stage value to the default task type. Falls back to 'brainstorm'
 * when the stage is unrecognized — this is safer than guessing 'build'
 * because brainstorming loads the lightest set of docs.
 *
 * @param {string} stage
 * @returns {string} a member of `listTaskTypes()`
 */
export function stageToDefaultTaskType(stage) {
  if (typeof stage !== 'string' || stage.length === 0) return 'brainstorm';
  return STAGE_TO_DEFAULT_TASK_TYPE[stage] || 'brainstorm';
}

/**
 * §9.4: enforce the canonical ordering UX → UI → Architecture → Build.
 * A task that requires a later-phase document during an earlier phase is
 * deferred (the question is recorded for the right phase to surface it).
 *
 *   - `architecture` task during ux/ui/brainstorm → deferred
 *   - `build` task during ux/ui → deferred (cannot start build before
 *     architecture decisions are settled)
 *   - `ui-implementation` task during ux → deferred (UI follows UX)
 *
 * Stages outside the canonical phase set (dashboard buckets / unknown) do
 * NOT trigger the gate — the orchestrator is expected to resolve a phase
 * via `currentPhase(slug, ...)` from `decision-gate.mjs` before calling
 * `resolveRoute` with a non-canonical stage.
 */
function shouldDefer(taskType, stage) {
  // Map taskType → minimum required phase index (when this task can run)
  const TASK_PHASE_REQUIREMENT = {
    'ux-decisions': 0,
    'ui-implementation': 1,
    architecture: 2,
    build: 3,
  };
  const required = TASK_PHASE_REQUIREMENT[taskType];
  if (required == null) return { deferred: false, reason: null };

  const currentIdx = PHASE_ORDER.indexOf(stage);
  if (currentIdx === -1) {
    // Non-canonical stage (e.g. dashboard bucket). Trust the caller.
    return { deferred: false, reason: null };
  }
  if (currentIdx < required) {
    const requiredPhase = PHASE_ORDER[required];
    return {
      deferred: true,
      reason:
        `The "${taskType}" route is only loaded during the ${requiredPhase} phase ` +
        `or later. Current phase is ${stage}. The question will be deferred until ` +
        `the ${requiredPhase} phase (UX → UI → Architecture → Build).`,
    };
  }
  return { deferred: false, reason: null };
}

/**
 * Substitute `{slug}` in a path. If `slug` is missing, return the path with
 * the literal `{slug}` token left in place and emit a console.warn.
 */
function substituteSlug(rawPath, slug, scope) {
  if (!rawPath.includes('{slug}')) return rawPath;
  if (!slug) {
    console.warn(
      `[mc-router] route doc "${scope}" requires {slug} but none was provided; leaving literal token in path: ${rawPath}`,
    );
    return rawPath;
  }
  return rawPath.replaceAll('{slug}', slug);
}

/**
 * Resolve `{slug}`-substituted path relative to controlRoot when controlRoot
 * is provided as an absolute project root, otherwise return as-is.
 */
function absolutizeForCheck(p, projectRoot) {
  if (!projectRoot) return p;
  if (path.isAbsolute(p)) return p;
  return path.join(projectRoot, p);
}

/**
 * Resolve a route: given a taskType (and optional stage/slug), return the
 * list of documents a subagent should load.
 *
 * @param {Object} args
 * @param {string} args.taskType - One of `listTaskTypes()`.
 * @param {('ux'|'ui'|'architecture'|'build')} [args.stage] - Current pipeline stage. Used for backtracking prevention.
 * @param {string} [args.slug] - Feature slug; substituted into `{slug}` placeholders.
 * @param {string} [args.controlRoot] - Absolute project root used by `verifyExists`. Should be the directory CONTAINING `control/v5/`, not `control/v5/` itself.
 * @param {boolean} [args.verifyExists=false] - If true, each doc gets an `exists` boolean determined by `fs.access`.
 * @returns {Promise<{taskType: string, stage: string|null, docs: Array<{path: string, scope: string, optional: boolean, exists?: boolean}>, deferred: boolean, deferredReason: string|null}>}
 *
 * @throws if `taskType` is not in `TASK_TYPE_ROUTES`.
 */
export async function resolveRoute({
  taskType,
  stage = null,
  slug = null,
  controlRoot = null,
  verifyExists = false,
} = {}) {
  if (!taskType || typeof taskType !== 'string') {
    throw new Error('resolveRoute: taskType must be a non-empty string');
  }
  const entry = TASK_TYPE_ROUTES[taskType];
  if (!entry) {
    throw new Error(
      `resolveRoute: unknown task type "${taskType}"; expected one of ${listTaskTypes().join('|')}`,
    );
  }

  const docList = entry.docs;
  const usageNote = entry.usageNote || null;

  const { deferred, reason } = shouldDefer(taskType, stage);
  if (deferred) {
    return {
      taskType,
      stage,
      docs: [],
      usageNote,
      deferred: true,
      deferredReason: reason,
    };
  }

  const docs = [];
  for (const routeDoc of docList) {
    const resolvedPath = substituteSlug(routeDoc.path, slug, routeDoc.scope);
    const doc = {
      path: resolvedPath,
      scope: routeDoc.scope,
      optional: !!routeDoc.optional,
    };
    if (verifyExists) {
      const abs = absolutizeForCheck(resolvedPath, controlRoot);
      try {
        await fs.access(abs);
        doc.exists = true;
      } catch {
        doc.exists = false;
      }
    }
    docs.push(doc);
  }

  return {
    taskType,
    stage,
    docs,
    usageNote,
    deferred: false,
    deferredReason: null,
  };
}
