/**
 * v5 router: maps task types to the documents a subagent needs.
 *
 * Implements §2 (Document Routing) and §9.4 (backtracking prevention) of
 * `docs/REFACTOR-REQUIREMENTS.md`. The shape is illustrated in
 * `docs/v5-diagrams/01-document-routing.html`.
 *
 * Design:
 * - The `TASK_TYPE_ROUTES` map is the single source of truth. Adding a new
 *   task type only requires extending this map.
 * - Each route is an ordered list of `{ path, scope, optional }`. `path` may
 *   contain `{slug}` which is substituted at resolve time.
 * - `resolveRoute` returns paths only — it does not read files. Use
 *   `lib/v5/context-packet.mjs` to load and size content.
 * - When `stage` is `ux` or `ui` and the requested taskType is `architecture`,
 *   the route is deferred (no docs returned) to prevent backtracking into
 *   architecture decisions while UX/UI are still being explored. §9 of
 *   `docs/REFACTOR-REQUIREMENTS.md` mandates strict UX → UI → Architecture →
 *   Build ordering.
 *
 * No external dependencies — stdlib only.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Hard rule about decision visual fragments. Surfaced verbatim into every
 * dispatch packet for UX, UI, and Architecture routes via `usageNote`. The
 * same wording appears in the four routing docs and the three v5 skills.
 *
 * Keep this string identical to the wording in:
 *   - control/v5/routing/UX-PATTERNS.md
 *   - control/v5/routing/UI-REQUIREMENTS.md
 *   - control/v5/routing/ARCHITECTURE.md
 *   - control/v5/routing/ROUTING-MANIFEST.md
 *   - skills/mc-v5/SKILL.md
 *   - skills/mc-v5-brainstorm/SKILL.md
 *   - skills/mc-v5-build/SKILL.md
 */
const VISUAL_FRAGMENT_RULE =
  'You MUST NOT write HTML for a decision card by hand. Every decision in ' +
  'decisions.json requires a sibling fragment file generated by ' +
  '`node lib/v5/cli/build-decision.mjs <slug> <decision-id>`. If a decision ' +
  'has no fragment, the feature page falls back to plain text cards — this ' +
  'is a failure mode, not an acceptable state.';

const ROUTING_DOCS_NOTE =
  'Consult the routing docs in `control/v5/routing/` before producing any ' +
  'visual artifacts. Do not hand-author decision card HTML — see the visual ' +
  'fragment contract in `control/v5/routing/ROUTING-MANIFEST.md`.';

/**
 * Canonical task type → route map.
 *
 * Each entry is `{ docs, usageNote }`:
 *  - `docs` is an ordered list of `{ path, scope, optional }`:
 *    - `path` is a repo-relative path. `{slug}` tokens are substituted by
 *      `resolveRoute` if a `slug` is provided.
 *    - `scope` is a short tag used in logging and UI display.
 *    - `optional` indicates the doc may not exist on disk (e.g., per-feature
 *      files that only appear after the feature has produced output).
 *  - `usageNote` is a string the router forwards into every context packet's
 *    `instructions[]` array. Used to surface the visual fragment contract
 *    (do not hand-write decision HTML) to dispatched subagents.
 */
export const TASK_TYPE_ROUTES = Object.freeze({
  'ui-implementation': {
    docs: [
      { path: 'control/v5/routing/UI-REQUIREMENTS.md', scope: 'ui-requirements', optional: false },
      {
        path: 'control/layout/diagrams/ui-options/template.html',
        scope: 'ui-primitives',
        optional: false,
      },
      {
        path: 'control/v5/features/{slug}/layout/wireframes/',
        scope: 'wireframes',
        optional: true,
      },
    ],
    usageNote: VISUAL_FRAGMENT_RULE,
  },
  'ux-decisions': {
    docs: [
      { path: 'control/v5/routing/UX-PATTERNS.md', scope: 'ux-patterns', optional: false },
      {
        path: 'control/layout/diagrams/ux-flow/template.html',
        scope: 'ux-primitives',
        optional: false,
      },
      {
        path: 'control/v5/features/{slug}/ux-flow.html',
        scope: 'current-flow',
        optional: true,
      },
    ],
    usageNote: VISUAL_FRAGMENT_RULE,
  },
  architecture: {
    docs: [
      { path: 'control/v5/routing/ARCHITECTURE.md', scope: 'architecture', optional: false },
      { path: 'control/v5/tech-stack/stack.json', scope: 'stack', optional: true },
      {
        path: 'control/layout/diagrams/architecture/template.html',
        scope: 'architecture-primitives',
        optional: false,
      },
    ],
    usageNote: VISUAL_FRAGMENT_RULE,
  },
  research: {
    docs: [
      { path: 'control/v5/routing/UX-PATTERNS.md', scope: 'patterns', optional: false },
      {
        path: 'control/v5/features/{slug}/braindump.md',
        scope: 'user-spec',
        optional: true,
      },
    ],
    usageNote: ROUTING_DOCS_NOTE,
  },
  build: {
    docs: [
      {
        path: 'control/v5/features/{slug}/phases/',
        scope: 'phase-plans',
        optional: false,
      },
      { path: 'control/v5/routing/BUILD-GATES.md', scope: 'build-gates', optional: false },
      {
        path: 'control/v5/features/{slug}/spec.md',
        scope: 'spec',
        optional: true,
      },
    ],
    usageNote: ROUTING_DOCS_NOTE,
  },
  brainstorm: {
    docs: [
      { path: 'control/v5/routing/UX-PATTERNS.md', scope: 'patterns', optional: false },
      {
        path: 'control/v5/features/{slug}/braindump.md',
        scope: 'product-context',
        optional: true,
      },
    ],
    usageNote: ROUTING_DOCS_NOTE,
  },
});

/**
 * Return the list of supported task types.
 *
 * @returns {string[]}
 */
export function listTaskTypes() {
  return Object.keys(TASK_TYPE_ROUTES);
}

/**
 * §9.4: refuse to load architecture documents while UX or UI are still being
 * decided. The question/task is recorded as deferred so it can be re-raised in
 * the architecture phase. §9 enforces the strict order UX → UI → Architecture
 * → Build; architecture must not be loaded until UI is complete.
 */
function shouldDefer(taskType, stage) {
  if (taskType === 'architecture' && (stage === 'ux' || stage === 'ui')) {
    return {
      deferred: true,
      reason:
        `Architecture documents are not loaded during the ${stage} phase. ` +
        'The question will be deferred until the architecture phase ' +
        '(UX → UI → Architecture → Build).',
    };
  }
  return { deferred: false, reason: null };
}

/**
 * Substitute `{slug}` in a path. If `slug` is missing, return the path with
 * the literal `{slug}` token left in place and emit a console.warn.
 */
function substituteSlug(rawPath, slug, scope) {
  if (!rawPath.includes('{slug}')) return rawPath;
  if (!slug) {
    console.warn(
      `[mc-router] route doc "${scope}" requires {slug} but none was provided; leaving literal token in path: ${rawPath}`,
    );
    return rawPath;
  }
  return rawPath.replaceAll('{slug}', slug);
}

/**
 * Resolve `{slug}`-substituted path relative to controlRoot when controlRoot
 * is provided as an absolute project root, otherwise return as-is.
 */
function absolutizeForCheck(p, projectRoot) {
  if (!projectRoot) return p;
  if (path.isAbsolute(p)) return p;
  return path.join(projectRoot, p);
}

/**
 * Resolve a route: given a taskType (and optional stage/slug), return the
 * list of documents a subagent should load.
 *
 * @param {Object} args
 * @param {string} args.taskType - One of `listTaskTypes()`.
 * @param {('ux'|'ui'|'architecture'|'build')} [args.stage] - Current pipeline stage. Used for backtracking prevention.
 * @param {string} [args.slug] - Feature slug; substituted into `{slug}` placeholders.
 * @param {string} [args.controlRoot] - Absolute project root used by `verifyExists`. Should be the directory CONTAINING `control/v5/`, not `control/v5/` itself.
 * @param {boolean} [args.verifyExists=false] - If true, each doc gets an `exists` boolean determined by `fs.access`.
 * @returns {Promise<{taskType: string, stage: string|null, docs: Array<{path: string, scope: string, optional: boolean, exists?: boolean}>, deferred: boolean, deferredReason: string|null}>}
 *
 * @throws if `taskType` is not in `TASK_TYPE_ROUTES`.
 */
export async function resolveRoute({
  taskType,
  stage = null,
  slug = null,
  controlRoot = null,
  verifyExists = false,
} = {}) {
  if (!taskType || typeof taskType !== 'string') {
    throw new Error('resolveRoute: taskType must be a non-empty string');
  }
  const entry = TASK_TYPE_ROUTES[taskType];
  if (!entry) {
    throw new Error(
      `resolveRoute: unknown task type "${taskType}"; expected one of ${listTaskTypes().join('|')}`,
    );
  }

  // Accept both the modern `{ docs, usageNote }` shape and the legacy
  // raw-array shape so external callers extending TASK_TYPE_ROUTES at runtime
  // do not break.
  const docList = Array.isArray(entry) ? entry : entry.docs;
  const usageNote = Array.isArray(entry) ? null : entry.usageNote || null;

  const { deferred, reason } = shouldDefer(taskType, stage);
  if (deferred) {
    return {
      taskType,
      stage,
      docs: [],
      usageNote,
      deferred: true,
      deferredReason: reason,
    };
  }

  const docs = [];
  for (const routeDoc of docList) {
    const resolvedPath = substituteSlug(routeDoc.path, slug, routeDoc.scope);
    const doc = {
      path: resolvedPath,
      scope: routeDoc.scope,
      optional: !!routeDoc.optional,
    };
    if (verifyExists) {
      const abs = absolutizeForCheck(resolvedPath, controlRoot);
      try {
        await fs.access(abs);
        doc.exists = true;
      } catch {
        doc.exists = false;
      }
    }
    docs.push(doc);
  }

  return {
    taskType,
    stage,
    docs,
    usageNote,
    deferred: false,
    deferredReason: null,
  };
}
